name: CI

on:
  push:
    branches: [ main ]
    # El paths se usa para que solo detecte un cambio en hangman-api
    paths: [ "hangman-api/**" ]
  pull_request:
    branches: [ main ]
    paths: [ "hangman-api/**" ]


jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: build and test
        working-directory: ./hangman-api
        run: |
          npm ci
          npm run build --if-present
          npm test

  