name: CD workflow

on:
  pull_request:
    branches: [ main ]
    paths: [ "hangman-api/**" ]
  # workflow_dispatch:
    
jobs:
  build:
    uses: ./.github/workflows/reusable-node-build.yaml
    with:
      node-version: 16
      working-directory: ./hangman-api
      artifact-name: build-code
  
  delivery:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifact (dist folder)
        uses: actions/download-artifact
        with:
          name: build-code
          path: hangman-api/dist/
      - name: Build Docker image
        working-directory: ./hangman-api
        run: docker build -t hangman-api-2024:$(date +%s) -f Dockerfile.workflow .