name: CD_workflow

on:
  pull_request:
    branches: [ main ]
    paths: [ "hangman-api/**" ]
  workflow_dispatch:
    
jobs:
  build:
    uses: ./.github/workflows/reusable-node-build.yaml
    with:
      node-version: 16
      working-directory: ./hangman-api
      artifact-name: build-code
  
  delivery:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifact (dist folder)
        uses: actions/download-artifact@v4
        with:
          name: build-code
          path: hangman-api/dist/
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ferguttz
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Setup Docker builder
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./hangman-api
          push: true
          tags: ferguttz/hangman-api-actions-2024:latest
          file: ./hangman-api/Dockerfile.workflow
      # - name: Build and push to docker
      #   working-directory: ./hangman-api
      #   env:
      #     DOCKER_USER: "ferguttz"
      #     DOCKER_REPOSITORY: "hangman-api-2024"
      #     DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      #   run: | 
      #     echo $DOCKER_PASSWORD | docker login --username $DOCKER_USER --password-stdin
      #     image=$DOCKER_USER/$DOCKER_REPOSITORY:$(date +%s)
      #     docker build -t image -f Dockerfile.workflow .
      #     docker push $image