name: CD_workflow

on:
  pull_request:
    branches: [ main ]
    paths: [ "hangman-api/**" ]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: hangman-api/package-lock.json
      - name: build
        working-directory: ./hangman-api
        run: |
          npm ci
          npm run build --if-present
      - name: Upload artifact (dist folfer)
        uses: actions/upload-artifact@v4
        with:
          name: build-code
          path: hangman-api/dist/
  
  delivery:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifact (dist folder)
        uses: actions/download-artifact@v4
        with:
          name: build-code
          path: hangman-api/dist/
      - name: Build Docker image
        working-directory: ./hangman-api
        env:
          DOCKER_USER: "fergttz"
          DOCKER_REPOSITORY: "hangman-api-2024"
          DOCKER_PASSWORD: ${{secret.DOCKER_PASSWORD}}
        run: | 
          echo $DOCKER_PASSWORD | docker login --username $DOCKER_USER --password-stdin
          image=$DOCKER_USER/$DOCKER_REPOSITORY:$(date +%s)
          docker build -t image -f Dockerfile.workflow .
          docker push $image