name: CI

on:
  push:
    branches: [ main ]
    paths: [ "hangman-api/**" ]
  pull_request:
    branches: [ main ]
    paths: [ "hangman-api/**" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Setup Node.js version
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 20
      - name: build
        working-directory: ./hangman-api
        run: |
          npm ci
          npm run build --if-present
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dependencies
          path: hangman-api
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Artifact (dependencies)
        uses: actions/upload-artifact@v4
        with:
          name: dependencies
          path: hangman-api/node_modules/
      - name: test
        working-directory: ./hangman-api
        run: npm test
  # audit:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #     - name: Audit
  #       run: java --version


  