name: CI

on:
  push:
    branches: [ main ]
    # El paths se usa para que solo detecte un cambio en hangman-api
    paths: [ "hangman-api/**" ]
  pull_request:
    branches: [ main ]
    paths: [ "hangman-api/**" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Setup Node.js version
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 20
      - name: build
        working-directory: ./hangman-api
        run: |
          npm ci
          npm run build --if-present
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: test
        working-directory: ./hangman-api
        run: |
          npm test

  