name: CI

on:
  push:
    branches: [ main ]
    # El paths se usa para que solo detecte un cambio en hangman-api
    paths: [ "hangman-api/**" ]
  pull_request:
    branches: [ main ]
    paths: [ "hangman-api/**" ]


jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17, 18, 20]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: build and test
        working-directory: ./hangman-api
        run: |
          npm ci
          npm run build --if-present
          npm test

  