name: Test get commodity price custom actions

on:
  workflow_dispatch:
  
jobs:
  get_commodity_price:
    runs-on: ubuntu-latest

    steps:
      - name: Get commodity price
        uses: gutiz24/get-commodity-price-action@v1.0.1
        with:
          commodity: 'silver'