name: Test get commodity price custom actions

on:
  workflow_dispatch:
  
jobs:
  get_commodity_price:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        commodity: ["gold", "SILVER"]
        currency: ["USD", "eur"]

    steps:
      - name: Get commodity price
        id: commodity_price
        uses: gutiz24/get-commodity-price-action@v1.0.2
        with:
          commodity: ${{ matrix.commodity }}
          currency: ${{ matrix.currency }}
      - name: Get output price
        run: echo "Price per ounce is ${{ steps.commodity_price.outputs.prcie }} ${{ matrix.currency }}"
        